sudo: false
language: cpp
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - zlib1g-dev
      - libgsl0-dev
      - libqt4-opengl-dev
      - g++-4.8
      - python3
compiler:
  - gcc
  - clang
env:
  - python_version=2
  - python_version=3
install: 
  - export NUMBER_OF_PROCESSORS=4
  - export PATH=`pwd`/release/bin:${PATH}
  - export EIGEN_CFLAGS=-I`pwd`/eigen
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - (hg clone https://bitbucket.org/eigen/eigen/; cd eigen; hg update 3.2)
script:
        - if [ ${python_version} = "3" ]; then python3 ./configure -assert && python3 ./build -nowarnings && ./run_tests; else ./configure -assert && ./build -nowarnings && ./run_tests; fi
after_failure: 
  - cat configure.log
  - cat build.log
  - cat testing/testing.log
